/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

/**
 * Auto generated
 */
@SuppressWarnings({"ShortClassName"})
public class App {
    /**
     * Test method
     * @return nothing
     */
    public String getGreeting() {
        return "Hello World!";
    }
}
